### ISSUE TITLE
Support SonarQube 7.9 LTS

### ISSUE THREAD

**Issue by kwin** [wttech/AEM-Rules-for-SonarQube#174]
Now that the new SonarQube LTS version is out (https://www.sonarqube.org/sonarqube-7-9-lts/), it would be nice to support it. I haven't tried yet to run it on this version, but according to the release notes at https://github.com/Cognifide/AEM-Rules-for-SonarQube/releases even the newest 1.0RC2 is only compatible with SonarQube up to version 7.7.

**Comment by chutch** [comment]
Hi @kwin,

I think it should be compatible, but we'll make sure. We were kind of waiting for this to happen to release the full version into the update center.

Thanks!

**Comment by josephrignanese** [comment]
@kwin @chutch were you successful with getting this working?

**Comment by jplucinski** [comment]
Hi! @chutch @kwin @josephrignanese v1.0-RC2 uses API that is compatible with 7.9 version. I've test it with following **Dockerfile**:

```
FROM sonarqube:7.9-community AS aemrulesqube81

RUN curl -Lk -o $SONARQUBE_HOME/extensions/plugins/aemrules-1.0-RC2.jar https://github.com/Cognifide/AEM-Rules-for-SonarQube/releases/download/v1.0-RC2/aemrules-1.0-RC2.jar
```

**Comment by toniedzwiedz** [comment]
Version 1.1 has been released but there's a little blunder that needs fixing before it can be downloaded from the Marketplace https://github.com/SonarSource/sonar-update-center-properties/pull/117
I'm on it.
