### ISSUE TITLE
Unable to get all the AEM rules after installing v1.2 to SonarQube

### ISSUE THREAD

**Issue by singhs1704** [wttech/AEM-Rules-for-SonarQube#203]
Hi Team, 

I have SonarQube Community Edition v8.2 installed on a Docker image and I have installed the latest AEM SQ Rules v1.2 plugin on it. After completing the installation and restarting the server I only get the HTL Quality Profile with 17 rules in it but I do not get any Java AEM rules or Quality profile installed into SonarQube. Could you please advise?

Thanks

**Comment by singhs1704** [comment]
Hi Team, 

has anyone faced this issue? Any pointers here would be very helpful. 

Thanks

**Comment by toniedzwiedz** [comment]
Hi @singhs1704, sorry I missed your message. I haven't seen this behaviour. Can you provide more detail as to what's going on? Are these rules not used by your analyss? Do you not see the rules at all when inspecting https://sonarqube.example.com/coding_rules ?

**Comment by singhs1704** [comment]
Hi @toniedzwiedz, when I go into the quality profiles section I can see an additional Quality profile by the name AEM HTL profile but that only has 19 rules in it. I would have expected approximately 117 custom AEM rules instead. Please let me know if this is incorrect?

**Comment by singhs1704** [comment]
Hi @toniedzwiedz Sorry for chasing again. Do you have any pointers for me on this issue?

**Comment by TianZuo555** [comment]
samething here

**Comment by toniedzwiedz** [comment]
Hi, most rules are related to Java code and they're tagged with _AEM_, as @TianZuo555 noted. This hasn't changed in any of the recent versions. @singhs1704 is it that the rules don't fire when expected or is it just about their potentially confusing location?

**Comment by toniedzwiedz** [comment]
Closing this one due to lack of activity. Please reopen if this is still an issue.
