### ISSUE TITLE
Availability in Marketplace?

### ISSUE THREAD

**Issue by alwa** [wttech/AEM-Rules-for-SonarQube#215]
Hi, this plugin is not listed in the Marketplace for SonarQube 8.9 LTS.
Even if listed It would still not be possible to install directly from the UI, however it (being listed) is a stamp of quality that the plugin is actively developed, etc.

**Comment by toniedzwiedz** [comment]
Hi, version 1.6 has been released. It should work with 8.9 LTS and it's available in the marketplace. Sorry for the long wait.
